#!/usr/bin/env bash

#===============Configuration====================================
path="$HOME/backups"     # Put here the root path
older_than="30"          # Age of the files to delete in days.
#================================================================

find $path -mtime +$older_than -exec rm {} \;
