#!/bin/bash

#===============Configuration====================================
path="$HOME/backups"     # Colocar aquí la ruta a los logs
older_than="30"          # Age of the files to delete in days.
#================================================================

find $path -mtime +$older_than -exec rm {} \;
