#!/usr/bin/python3
import os
import sys

if __name__ == '__main__':
  cmd_get_process_list = 'ps -ef --sort=start_time  | grep ssh-agent | grep -v grep'
  output = os.popen(cmd_get_process_list)
  lines = output.read().split("\n")
  output.close()
  if len(lines) < 3:
      print('kill_old_ssh_agents: You\'re good, nothing to kill')
      sys.exit(0)
  
  for line in lines[:-2]:
      cmd = 'kill -9 ' +  line.split()[1]
      print('kill_old_ssh_agents: ' + cmd)
      os.system(cmd)
  
