#!/usr/bin/env bash
#set -x

# SYSLOG PATH IN LINUX
SYSLOG_PATH=/var/log/syslog

if [[ `uname -s` == 'Darwin' ]]
then
    echo "We are in Darwin"
    SYSLOG_PATH=/private/var/log/system.log
fi
echo "Tail-effing ${SYSLOG_PATH}"
tail -f ${SYSLOG_PATH}
