#!/bin/bash
if [[ ! -f ./wp-config.php ]]; then
  echo "Please execute wp_upgrade inside your wordpress folder."
  return 1
fi
  
sudo chmod 0777 * -R

echo "Permissions ready, purging tilde files..."
purgeTildes 

echo "wp_fix_permissions_for_upgrade, you're now ready to upgrade wordpress and plugins, make sure to execute wp_fix_permissions when you're done."